name: Trojan VPN Checker

on:
  schedule:
    - cron: '0 * * * *'  # Jalankan setiap jam
  workflow_dispatch:  # Izinkan pemicu manual

jobs:
  check-trojan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # penting supaya bisa rebase sebelum push

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests speedtest-cli

      - name: Run Trojan checker
        run: python trojan_checker.py

      - name: Setup Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Commit results
        run: |
          git add active_trojan_urls.txt
          git commit -m "Update Trojan URLs check - $(date -u +'%Y-%m-%d %H:%M:%S UTC')" || echo "No changes to commit"

      - name: Push changes
        run: |
          git pull --rebase origin main || true
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main

      - name: Upload results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: trojan-check-results
          path: active_trojan_urls.txt
          retention-days: 7
